# Managing Kleio files

> First time use: follow instructions in the [README.md](README.md) file in this directory.

## Initial setup

Create a TimelinkNotebook object. This will be the interface for most of your interactions with Timelink.

The first time you run this notebook, you will be prompted to install ìpykernel. This is required to run Timelink in a notebook.

Note:
* First time run takes a little time as the required Docker images are downloaded.
* Timelink will default to using sqlite as the database, see [Receipts notebook for more control](1-receipts.ipynb)

In [2]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()
tlnb.print_info()

WARNING:root:Reusing existing container nifty_yonath

Timelink version: 1.2.0
Project name: obidos-fontes
Project home: /Users/jrc/mhk-home/sources/obidos-fontes
Database type: sqlite
Database name: obidos_fontes
Kleio image: timelinkserver/kleio-server
Kleio server token: 7009D...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/mhk-home/sources/obidos-fontes
Kleio server container: nifty_yonath
Kleio version requested: latest
Kleio server container status: running
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/mhk-home/sources/obidos-fontes/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=obidos-fontes, project_home=/Users/jrc/mhk-home/sources/obidos-fontes, db_type=sqlite, db_name=obidos_fontes, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

TimelinkNotebook created a database to store data and a Kleio server to 
translate transcriptions in Kleio notation into data that can be imported
into a database.

To get information about the database and the Kleio server do ```tnlb.print_info()```

### Database status

Count the number of rows in each table in the database.

In [3]:
tlnb.table_row_count_df()

               table   count
0               acts   12357
1    alembic_version       1
2         aregisters       0
3         attributes   75145
4             blinks       0
5   class_attributes      58
6            classes      10
7           entities  301197
8        geoentities       0
9         kleiofiles     231
10             links    1605
11           objects       0
12           persons   76819
13         relations  135862
14         rentities     773
15           sources     231
16            syslog       0
17            syspar       0

### Show the kleio files available

In [4]:
import pandas as pd

pd.set_option("display.max_rows", 500)

kleio_files = tlnb.get_kleio_files()

file_colums = ['name','status','errors','warnings', 'translated',  'import_status', 'import_errors', 'import_warnings','imported']
kleio_files[file_colums]

,name,status,errors,warnings,translated,import_status,import_errors,import_warnings,imported
0,SJ-1556-1604.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:55:54.481098
1,SJ-1574-1577.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:55:57.758233
2,SJ-1601-1611.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:03.984820
3,SJ-1611-1614.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:07.267389
4,SJ-1615-1620.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:16.951227
5,SJ-1621-1625.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:23.323764
6,SJ-1626-1630.cli,W,0,1,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 14:56:31.833318
7,SJ-1631-1635.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:38.224315
8,SJ-1636-1640.cli,W,0,46,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:46.626443
9,SJ-1641-1645.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:54.057129
10,SJ-1646-1649.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:00.852629
11,SJ-1650-1655.cli,W,0,3,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:08.995756
12,SJ-1656-1660.cli,W,0,2,2026-10-13 10:18:00+00:00,N,0,0,NaT
13,SJ-1661-1665.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:14.801733
14,SJ-1666-1670.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:21.367815
15,SJ-1671-1680.cli,E,2,3,2026-10-12 06:10:00+00:00,N,0,0,NaT
16,SJ-1681-1685.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:30.091370
17,SJ-1686-1690.cli,W,0,3,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:42.912856
18,SJ-1691-1697.cli,W,0,8,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:56.476017
19,SJ-1698-1700.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:58:03.862778
20,SJ-1701-1702.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:58:16.843605
21,SJ-1703-1704.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:59:13.558129
22,SJ-1705-1706.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:59:21.081209
23,SJ-1707-1708.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:28.306923
24,SJ-1709-1710.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:36.121424
25,SJ-1711-1712.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:41.225458
26,SJ-1713-1714.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:49.138031
27,SJ-1715-1716.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:57.637989
28,SJ-1717-1718.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:04.736833
29,SJ-1719-1720.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:12.535274
30,SJ-1721-1722.cli,E,1,2,2026-10-12 06:11:00+00:00,N,0,0,NaT
31,SJ-1723-1724.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:20.081107
32,SJ-1725-1727.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:31.124137
33,SJ-1727-1729.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:43.148718
34,SJ-1729-1731.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:50.094365
35,SJ-1732-1733.cli,E,1,1,2026-10-12 06:11:00+00:00,N,0,0,NaT
36,SJ-1734-1735.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:56.353300
37,SJ-1736-1737.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:01.733330
38,SJ-1738-1739.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:06.864231
39,SJ-1740-1741.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:14.572256
40,SJ-1742-1743.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:23.470793
41,SJ-1744-1745.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:04:46.210006
42,SJ-1745-1746.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:05:46.346975
43,SJ-1747-1748.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:06:30.048051
44,SJ-1749-1750.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:07:13.547600
45,SJ-1751-1752.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:07:48.451266
46,SJ-1753-1754.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:08:23.413842
47,SJ-1755-1756.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:09:22.933552
48,SJ-1757-1758.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:10:05.413562
49,SJ-1759-1760.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:10:28.662415
50,SJ-1761-1762.cli,E,1,2,2026-10-12 06:12:00+00:00,N,0,0,NaT
51,SJ-1763-1764.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:10:47.644973
52,SJ-1765-1766.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:08.476477
53,SJ-1767-1768.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:30.355082
54,SJ-1769-1770.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:57.017318
55,SJ-1771-1772.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:12:18.057870
56,SJ-1773-1774.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:12:49.738999
57,SJ-1775-1776.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:13:23.254391
58,SJ-1777-1778.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:13:57.569667
59,SJ-1779-1780.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:14:29.283289
60,SJ-1781-1782.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:16:11.646049
61,SJ-1783-1784.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:19:21.930654
62,SJ-1785-1786.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:21:18.859295
63,SJ-1787-1788.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:22:02.407391
64,SJ-1789-1790.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:22:52.287602
65,SJ-1791-1792.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:23:23.498863
66,SJ-1793-1794.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:24:05.573557
67,SJ-1795-1796.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:24:33.169354
68,SJ-1797-1798.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:25:37.262334
69,SJ-1799-1800.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:21.831890
70,SJ-cas1541-1635.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:29.993169
71,SJ-cas1702-1707.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:44.448668
72,SJ-cas1708-1718.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:27:06.700598
73,SJ-cas1719-1726.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:27:46.880646
74,SJ-cas1727-1732.cli,T,7,8,2026-10-12 06:13:00+00:00,N,0,0,NaT
75,SJ-cas1733-1737.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:28:17.782562
76,SJ-cas1738-1739.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:28:27.675109
77,SJ-cas1740-1749.cli,E,10,11,2026-10-12 06:14:00+00:00,N,0,0,NaT
78,SJ-cas1750-1760.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:29:34.809641
79,SJ-cas1761-1770.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:30:37.380827
80,SJ-cas1771-1780.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:31:26.715777
81,SJ-cas1781-1790.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:32:33.585227
82,SJ-cas1791-1800.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:33:33.970349
83,SJ-o1538-1559.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
84,SJ-o1560-1569.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
85,SJ-o1584-1585.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
86,SJ-o1586-1590.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
87,SJ-o1591-1595.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
88,SJ-o1596-1600.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
89,SJ-o1601-1605.cli,W,0,3,2026-10-12 06:15:00+00:00,N,0,0,NaT
90,SJ-o1606-1609.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
91,SJ-o1616-1620.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
92,SJ-o1621-1625.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
93,SJ-o1622-1623.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
94,SJ-o1626-1630.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
95,SJ-o1631-1635.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
96,SJ-o1636-1640.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
97,SJ-o1641-1645.cli,W,0,2,2026-10-12 06:15:00+00:00,N,0,0,NaT
98,SJ-o1646-1650.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
99,SJ-o1651-1655.cli,W,0,4,2026-10-12 06:15:00+00:00,N,0,0,NaT
100,SJ-o1656-1660.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
101,SJ-o1661-1670.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
102,SJ-o1671-1680.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
103,SJ-o1681-1690.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
104,SJ-o1691-1701.cli,W,0,1,2026-10-13 10:24:00+00:00,N,0,0,NaT
105,SJ-o1702-1710.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
106,SJ-o1711-1720.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
107,SJ-o1721-1725.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
108,SJ-o1726-1730.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
109,SJ-o1731-1735.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
110,SJ-o1736-1739.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
111,SJ-o1740-1745.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
112,SJ-o1746-1750.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
113,SJ-o1751-1755.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
114,SJ-o1756-1760.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
115,SJ-o1761-1765.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
116,SJ-o1766-1770.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
117,SJ-o1771-1775.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
118,SJ-o1776-1780.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
119,SJ-o1781-1785.cli,W,0,1,2026-10-13 10:24:00+00:00,N,0,0,NaT
120,SJ-o1786-1790.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
121,SJ-o1791-1793.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
122,SJ-o1794-1795.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
123,SJ-o1796-1800.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
124,ST o1759-1761.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
125,ST o1762-1769.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
126,ST o1770-1774.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
127,ST o1774-1779.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
128,ST o1780-1782.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
129,ST o1783-1786.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
130,ST o1787-1791.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
131,ST o1792-1796.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
132,ST o1797-1800.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
133,ST obit1751-1755.cli,W,0,1,2026-10-12 06:18:00+00:00,N,0,0,NaT
134,ST obit1756-1758.cli,W,0,1,2026-10-12 06:18:00+00:00,N,0,0,NaT
135,ST-1600-1608.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:34:19.430128
136,ST-1609-1616.cli,T,4,5,2026-10-12 06:18:00+00:00,N,0,0,NaT
137,ST-1616-1624.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:34:56.109711
138,ST-1624-1631.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:35:29.347045
139,ST-1631-1640.cli,T,5,6,2026-10-12 06:18:00+00:00,N,0,0,NaT
140,ST-1640-1643.cli,T,27,28,2026-10-12 06:18:00+00:00,N,0,0,NaT
141,ST-1685-1694.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:10.214362
142,ST-1694-1703.cli,T,35,36,2026-10-12 06:19:00+00:00,N,0,0,NaT
143,ST-1703-1710.cli,T,21,22,2026-10-12 06:19:00+00:00,N,0,0,NaT
144,ST-1710-1716.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:30.399075
145,ST-1716-1719.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:41.545280
146,ST-1719-1722.cli,E,1,2,2026-10-12 06:19:00+00:00,N,0,0,NaT
147,ST-1723-1726.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:50.726767
148,ST-1726-1729.cli,T,2,4,2026-10-12 06:20:00+00:00,N,0,0,NaT
149,ST-1730-1733.cli,T,2,3,2026-10-12 06:20:00+00:00,N,0,0,NaT
150,ST-1733-1736.cli,E,2,3,2026-10-12 06:20:00+00:00,N,0,0,NaT
151,ST-1737-1740.cli,E,1,2,2026-10-12 06:20:00+00:00,N,0,0,NaT
152,ST-1740-1743.cli,E,1,2,2026-10-12 06:20:00+00:00,N,0,0,NaT
153,ST-1743-1747.cli,W,0,1,2026-10-12 06:20:00+00:00,I,0,0,2026-10-12 15:37:03.384709
154,ST-1747.cli,W,0,1,2026-10-12 06:20:00+00:00,I,0,0,2026-10-12 15:37:06.912080
155,ST-1764-1766.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:14.265459
156,ST-1767-1769.cli,E,1,4,2026-10-12 06:21:00+00:00,N,0,0,NaT
157,ST-1770-1773.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:21.894859
158,ST-1773-1776.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:29.068873
159,ST-1776-1779.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:37.264681
160,ST-1779-1782.cli,W,0,2,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:48.223389
161,ST-1783-1785.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:38:04.882855
162,ST-1785-1788.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:38:18.934370
163,ST-1789-1792.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:38:36.431775
164,ST-1792-1795.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:38:45.507134
165,ST-1796-1800.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:15.229842
166,ST-c1599-1624.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:22.761457
167,ST-c1624-1644.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:40.606841
168,ST-c1695-1705.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:58.299862
169,ST-c1706-1721.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:16.012466
170,ST-c1722-1730.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:31.990590
171,ST-c1731-1740.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:55.406327
172,ST-c1741-1750.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:41:22.387760
173,ST-c1751-1760.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:41:40.528629
174,ST-c1761-1775.cli,E,1,2,2026-10-12 06:23:00+00:00,N,0,0,NaT
175,ST-c1776-1792.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:41:53.934117
176,ST-c1793-1800.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:03.883282
177,ST-o1599-1626.cli,W,0,1,2026-10-12 06:23:00+00:00,N,0,0,NaT
178,ST-o1626-1631.cli,W,0,1,2026-10-12 06:23:00+00:00,N,0,0,NaT
179,ST-o1632-1643.cli,W,0,9,2026-10-12 06:23:00+00:00,N,0,0,NaT
180,notarial1704.cli,W,0,1,2026-10-13 14:59:00+00:00,N,0,0,NaT
181,notarial1705.cli,T,0,11,2026-10-13 14:54:00+00:00,N,0,0,NaT
182,santamaria-1562-1563.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:06.960262
183,santamaria-1563-1565.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:14.201826
184,santamaria-1566-1570.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:36.137971
185,santamaria-1571-1575.cli,W,0,2,2026-10-13 15:08:00+00:00,N,0,0,NaT
186,santamaria-1576-1580.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:42:58.766210
187,santamaria-1581-1584.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:43:10.885025
188,santamaria-1585-1590.cli,T,3,5,2026-10-12 06:24:00+00:00,N,0,0,NaT
189,santamaria-1591-1595.cli,T,3,5,2026-10-12 06:24:00+00:00,N,0,0,NaT
190,santamaria-1596-1599.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:43:22.588234
191,santamaria-1599-1604.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:43:47.082280
192,santamaria-1604-1605.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:43:52.339162
193,santamaria-1606-1610.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:13.597686
194,santamaria-1611-1615.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:28.607120
195,santamaria-1616-1620.cli,W,0,3,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:44:40.733982
196,santamaria-1621-1625.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:51.573860
197,santamaria-1625-1629.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:02.060647
198,santamaria-1630-1634.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:14.728713
199,santamaria-1635-1640.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:29.046279
200,santamaria-1641-1645.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:42.909895
201,santamaria-1646-1650.cli,T,4,6,2026-10-13 10:24:00+00:00,N,0,0,NaT
202,santamaria-1651-1655.cli,T,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
203,santamaria-1656-1660.cli,T,5,8,2026-10-12 06:24:00+00:00,N,0,0,NaT
204,santamaria-1661-1665.cli,T,3,6,2026-10-12 06:24:00+00:00,N,0,0,NaT
205,santamaria-1666-1670.cli,W,0,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
206,santamaria-1671-1675.cli,W,0,3,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:45:53.172179
207,santamaria-1676-1680.cli,W,0,4,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:04.450913
208,santamaria-1681-1685.cli,W,0,2,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:14.007345
209,santamaria-1686-1690.cli,W,0,3,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:27.718536
210,santamaria-1691-1695.cli,W,0,3,2026-10-13 15:11:00+00:00,N,0,0,NaT
211,santamaria-1696-1700.cli,T,4,7,2026-10-13 06:19:00+00:00,N,0,0,NaT
212,santamaria-1701-1705.cli,W,0,2,2026-10-13 06:19:00+00:00,N,0,0,NaT
213,santamaria-1706-1710.cli,T,2,5,2026-10-12 06:25:00+00:00,N,0,0,NaT
214,santamaria-1711-1715.cli,W,0,2,2026-10-13 15:04:00+00:00,N,0,0,NaT
215,santamaria-1716-1720.cli,T,2,11,2026-10-12 06:25:00+00:00,N,0,0,NaT
216,santamaria-1721-1725.cli,T,1,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
217,santamaria-1726-1730.cli,W,0,2,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:43.705050
218,santamaria-1731-1735.cli,T,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
219,santamaria-1736-1740.cli,T,19,21,2026-10-13 10:25:00+00:00,N,0,0,NaT
220,santamaria-1741-1743.cli,T,12,16,2026-10-13 10:25:00+00:00,N,0,0,NaT
221,santamaria-1744-1745.cli,E,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
222,santamaria-1746-1750.cli,E,1,3,2026-10-12 06:26:00+00:00,N,0,0,NaT
223,santamaria-1751-1753.cli,W,0,5,2026-10-13 06:19:00+00:00,N,0,0,NaT
224,santamaria-1754-1755.cli,W,0,3,2026-10-13 06:19:00+00:00,N,0,0,NaT
225,santamaria-1756-1758.cli,E,1,3,2026-10-13 10:26:00+00:00,N,0,0,NaT
226,santamaria-1759-1760.cli,W,0,2,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:46:55.385632
227,santamaria-1761-1765.cli,E,1,4,2026-10-12 06:26:00+00:00,N,0,0,NaT
228,santamaria-1766-1770.cli,W,0,3,2026-10-13 15:12:00+00:00,N,0,0,NaT
229,santamaria-1771-1774.cli,W,0,7,2026-10-13 06:19:00+00:00,N,0,0,NaT
230,santamaria-1775.cli,E,1,2,2026-10-12 06:26:00+00:00,N,0,0,NaT
231,santamaria-1776-1781.cli,E,1,2,2026-10-13 15:13:00+00:00,N,0,0,NaT
232,santamaria-1782.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:01.004696
233,santamaria-1783.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:05.034417
234,santamaria-1784.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:08.090386
235,santamaria-1785.cli,E,1,2,2026-10-12 06:26:00+00:00,N,0,0,NaT
236,santamaria-1786.cli,W,0,1,2026-10-13 15:14:00+00:00,N,0,0,NaT
237,santamaria-1787-1788.cli,W,0,1,2026-10-13 15:15:00+00:00,N,0,0,NaT
238,santamaria-1789-1791.cli,W,0,2,2026-10-13 15:16:00+00:00,N,0,0,NaT
239,santamaria-1792-1794.cli,E,10,2,2026-10-12 06:27:00+00:00,N,0,0,NaT
240,santamaria-1795.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:13.919623
241,santamaria-1796.cli,E,3,2,2026-10-12 06:27:00+00:00,N,0,0,NaT
242,santamaria-1797.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:20.883700
243,santamaria-1798-1800.cli,E,2,3,2026-10-12 06:27:00+00:00,N,0,0,NaT
244,santamaria-c1566-1570.cli,E,2,3,2026-10-13 10:26:00+00:00,N,0,0,NaT
245,santamaria-c1571-1575.cli,W,0,2,2026-10-13 06:19:00+00:00,N,0,0,NaT
246,santamaria-c1576-1580.cli,W,0,2,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:24.369460
247,santamaria-c1581-1585.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:28.073768
248,santamaria-c1586-1590.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:31.076166
249,santamaria-c1591-1595.cli,W,0,1,2026-10-13 10:26:00+00:00,N,0,0,NaT
250,santamaria-c1596-1600.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:33.631759
251,santamaria-c1601-1605.cli,W,0,1,2026-10-13 10:27:00+00:00,N,0,0,NaT
252,santamaria-c1606-1610.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
253,santamaria-c1611-1615.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
254,santamaria-c1616-1620.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
255,santamaria-c1621-1625.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:36.131761

## Optionally clean translations

In [ ]:
# tlnb.kleio_server.translation_clean("", recurse="yes")

['kleio/real-entities/real-entities.cli',
 'kleio/dehergne-locations-1644.cli',
 'kleio/dehergne-a.cli',
 'kleio/b1685.cli']


# Update the database from Kleio sources.

Updates source translations and imports into database sources with no errors.

Only changed files since last import, or new files, will be processed.

In [9]:
import logging
logging.basicConfig(level=logging.INFO)

tlnb.update_from_sources()
# get the import status
import_status = tlnb.get_import_status()
# list those with import_error > 0 or error > 0
errors = import_status.query("import_errors > 0 or errors > 0")
if len(errors) > 0:
    print(errors)

INFO:root:Request translation of T sources/paroquiais/sjoao/Baptismos/SJ-1626-1630.cli
INFO:root:Request translation of T sources/notariais/joao ferreira serra/notarial1705.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1576-1580.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1581-1584.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1596-1599.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1616-1620.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1625-1629.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1630-1634.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1635-1640.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Baptismos/santamaria-1641-1645.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Casamentos/santamaria-c1686-1690.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Casamentos/santamaria-c1721-1725.cli
INFO:root:Request translation of T sources/paroquiais/santamaria/Casamentos/santamaria-c1741-1745.cli
ERROR:root:Translation of sources/notariais/joao ferreira serra/notarial1705.cli finished with errors; file will not be imported
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1556-1604.cli
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:722: UserWarning: Ambiguous mapping! more than one element of n is mapped to column class sex check mapping for this group
  element: KElement = group.get_element_by_name_or_class(cattr.colclass)
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1574-1577.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1601-1611.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1611-1614.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1615-1620.cli
INFO:root:Storing 2 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1621-1625.cli
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1624-11 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1626-1630.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1631-1635.cli
INFO:root:Storing 1 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1636-1640.cli
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-4 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-5 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-6 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-7 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-8 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-9 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-10 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-11 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-12 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-13 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-14 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-15 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-16 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-17 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-18 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1638-19 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-4 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-6 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-7 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-8 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-9 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-10 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-11 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-12 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-13 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-14 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-15 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-16 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-17 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-18 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-19 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-20 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-21 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-23 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-24 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-25 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-26 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-27 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-28 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-29 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1639-30 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1640-1 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1640-2 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1640-3 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1640-4 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
INFO:root:Storing 1 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1641-1645.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1646-1649.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1650-1655.cli
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1653-5 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
/Users/jrc/mhk-home/sources/obidos-fontes/.venv/lib/python3.12/site-packages/timelink/api/models/pom_som_mapper.py:827: UserWarning: Element loc of group bap:sjoao-b1654-5 is too long for column loc of class act truncating to 64 characters
  entity_from_group: Entity = cls.kgroup_to_entity(group, session)
INFO:root:Storing 2 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1661-1665.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1666-1670.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1681-1685.cli
INFO:root:Storing 3 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1686-1690.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1691-1697.cli
INFO:root:Storing 4 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1698-1700.cli
INFO:root:Storing 2 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1701-1702.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1703-1704.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1705-1706.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1707-1708.cli
INFO:root:Storing 1 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1709-1710.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1711-1712.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1713-1714.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1715-1716.cli
INFO:root:Storing 1 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1717-1718.cli
INFO:root:Storing 1 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1719-1720.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1723-1724.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1725-1727.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1727-1729.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1729-1731.cli
INFO:root:Storing 2 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1734-1735.cli
INFO:root:Storing 2 postponed relations
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1736-1737.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1738-1739.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1740-1741.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1742-1743.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1744-1745.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1745-1746.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1747-1748.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1749-1750.cli
INFO:root:Importing sources/paroquiais/sjoao/Baptismos/SJ-1751-1752.cli

                                                  path  \
12   sources/paroquiais/sjoao/Baptismos/SJ-1656-166...
15   sources/paroquiais/sjoao/Baptismos/SJ-1671-168...
30   sources/paroquiais/sjoao/Baptismos/SJ-1721-172...
35   sources/paroquiais/sjoao/Baptismos/SJ-1732-173...
50   sources/paroquiais/sjoao/Baptismos/SJ-1761-176...
..                                                 ...
439  sources/paroquiais/spedro/Óbitos/saopedro-o17...
441  sources/paroquiais/spedro/Óbitos/saopedro-o17...
445  sources/paroquiais/vau/Casamentos/vau-c1761-17...
454  sources/paroquiais/vau/Óbitos/vau-o1761-1765.cli
456  sources/paroquiais/vau/Óbitos/vau-o1771-1775.cli

                        name    size                           directory  \
12          SJ-1656-1660.cli   45210  sources/paroquiais/sjoao/Baptismos
15          SJ-1671-1680.cli  105246  sources/paroquiais/sjoao/Baptismos
30          SJ-1721-1722.cli   32633  sources/paroquiais/sjoao/Baptismos
35          SJ-1732-1733.cli   30961  sources/paroquiais/sjoao/Baptismos
50          SJ-1761-1762.cli   36276  sources/paroquiais/sjoao/Baptismos
..                       ...     ...                                 ...
439  saopedro-o1790-1791.cli   20645   sources/paroquiais/spedro/Óbitos
441  saopedro-o1794-1795.cli   15165   sources/paroquiais/spedro/Óbitos
445       vau-c1761-1765.cli   11814   sources/paroquiais/vau/Casamentos
454       vau-o1761-1765.cli   22438      sources/paroquiais/vau/Óbitos
456       vau-o1771-1775.cli   13840      sources/paroquiais/vau/Óbitos

                            modified              modified_iso  \
12         2017-08-05 16:00:36+00:00 2017-08-05 16:00:36+00:00
15  2026-10-12 04:58:35.596679+00:00 2026-10-12 04:58:35+00:00
30         2009-03-20 17:27:48+00:00 2009-03-20 17:27:48+00:00
35         2009-03-20 17:27:48+00:00 2009-03-20 17:27:48+00:00
50         2009-03-20 17:27:48+00:00 2009-03-20 17:27:48+00:00
..                               ...                       ...
439 2026-10-12 15:07:54.180008+00:00 2026-10-12 15:07:54+00:00
441 2026-10-12 04:58:36.161708+00:00 2026-10-12 04:58:36+00:00
445 2026-10-12 04:58:36.214153+00:00 2026-10-12 04:58:36+00:00
454 2026-10-12 04:58:36.224786+00:00 2026-10-12 04:58:36+00:00
456 2026-10-12 15:07:54.180974+00:00 2026-10-12 15:07:54+00:00

         modified_string                     qtime         qtime_string  \
12   2017-08-05 16:00:36 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
15   2026-10-12 04:58:35 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
30   2009-03-20 17:27:48 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
35   2009-03-20 17:27:48 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
50   2009-03-20 17:27:48 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
..                   ...                       ...                  ...
439  2026-10-12 15:07:54 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
441  2026-10-12 04:58:36 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
445  2026-10-12 04:58:36 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
454  2026-10-12 04:58:36 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00
456  2026-10-12 15:07:54 1970-01-01 00:00:00+00:00  1970-01-01 00:00:00

                                            source_url  ...  \
12   /rest/sources/sources/paroquiais/sjoao/Baptism...  ...
15   /rest/sources/sources/paroquiais/sjoao/Baptism...  ...
30   /rest/sources/sources/paroquiais/sjoao/Baptism...  ...
35   /rest/sources/sources/paroquiais/sjoao/Baptism...  ...
50   /rest/sources/sources/paroquiais/sjoao/Baptism...  ...
..                                                 ...  ...
439  /rest/sources/sources/paroquiais/spedro/O%CC%8...  ...
441  /rest/sources/sources/paroquiais/spedro/O%CC%8...  ...
445  /rest/sources/sources/paroquiais/vau/Casamento...  ...
454  /rest/sources/sources/paroquiais/vau/O%CC%81bi...  ...
456  /rest/sources/sources/paroquiais/vau/O%CC%81bi...  ...

                                               version  \
12   KleioTranslator - server version 12.9 - build ...
15   KleioTranslator - server version 12.9 - build ...
30   KleioTranslator - server version 12.9 - build ...
35   KleioTranslator - server version 12.9 - build ...
50   KleioTranslator - server version 12.9 - build ...
..                                                 ...
439  KleioTranslator - server version 12.9 - build ...
441  KleioTranslator - server version 12.9 - build ...
445  KleioTranslator - server version 12.9 - build ...
454  KleioTranslator - server version 12.9 - build ...
456  KleioTranslator - server version 12.9 - build ...

                                               rpt_url  \
12   /rest/reports/sources/paroquiais/sjoao/Baptism...
15   /rest/reports/sources/paroquiais/sjoao/Baptism...
30   /rest/reports/sources/paroquiais/sjoao/Baptism...
35   /rest/reports/sources/paroquiais/sjoao/Baptism...
50   /rest/reports/sources/paroquiais/sjoao/Baptism...
..                                                 ...
439  /rest/reports/sources/paroquiais/spedro/O%CC%8...
441  /rest/reports/sources/paroquiais/spedro/O%CC%8...
445  /rest/reports/sources/paroquiais/vau/Casamento...
454  /rest/reports/sources/paroquiais/vau/O%CC%81bi...
456  /rest/reports/sources/paroquiais/vau/O%CC%81bi...

                                               xml_url  import_status  \
12   /rest/exports/sources/paroquiais/sjoao/Baptism...              N
15   /rest/exports/sources/paroquiais/sjoao/Baptism...              N
30   /rest/exports/sources/paroquiais/sjoao/Baptism...              N
35   /rest/exports/sources/paroquiais/sjoao/Baptism...              N
50   /rest/exports/sources/paroquiais/sjoao/Baptism...              N
..                                                 ...            ...
439  /rest/exports/sources/paroquiais/spedro/O%CC%8...              N
441  /rest/exports/sources/paroquiais/spedro/O%CC%8...              N
445  /rest/exports/sources/paroquiais/vau/Casamento...              N
454  /rest/exports/sources/paroquiais/vau/O%CC%81bi...              N
456  /rest/exports/sources/paroquiais/vau/O%CC%81bi...              N

     import_errors import_warnings import_error_rpt import_warning_rpt  \
12               0               0             None               None
15               0               0             None               None
30               0               0             None               None
35               0               0             None               None
50               0               0             None               None
..             ...             ...              ...                ...
439              0               0             None               None
441              0               0             None               None
445              0               0             None               None
454              0               0             None               None
456              0               0             None               None

    imported  imported_string
12       NaT             None
15       NaT             None
30       NaT             None
35       NaT             None
50       NaT             None
..       ...              ...
439      NaT             None
441      NaT             None
445      NaT             None
454      NaT             None
456      NaT             None

[126 rows x 25 columns]

## Check the status of the files

Check the import status of the translated files

* I: Imported
* E: Imported with error
* W: Imported with warnings no errors
* N: Not imported
* U: Translation updated need to reimport

In [21]:
imported_files_df = tlnb.get_import_status()
imported_files_df.info()
imported_files_df[file_colums].sort_values("name")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   path                462 non-null    object
 1   name                462 non-null    object
 2   size                462 non-null    int64
 3   directory           462 non-null    object
 4   modified            462 non-null    datetime64[ns, UTC]
 5   modified_iso        462 non-null    datetime64[ns, UTC]
 6   modified_string     462 non-null    object
 7   qtime               462 non-null    datetime64[ns, UTC]
 8   qtime_string        462 non-null    object
 9   source_url          462 non-null    object
 10  status              462 non-null    object
 11  translated          462 non-null    datetime64[ns, UTC]
 12  translated_string   462 non-null    object
 13  errors              462 non-null    int64
 14  warnings            462 non-null    int64
 15  version             462 non-null    object
 16  rpt_url             462 non-null    object
 17  xml_url             462 non-null    object
 18  import_status       462 non-null    object
 19  import_errors       462 non-null    Int64
 20  import_warnings     462 non-null    Int64
 21  import_error_rpt    231 non-null    object
 22  import_warning_rpt  231 non-null    object
 23  imported            231 non-null    datetime64[ns]
 24  imported_string     231 non-null    object
dtypes: Int64(2), datetime64[ns, UTC](4), datetime64[ns](1), int64(3), object(15)
memory usage: 91.3+ KB

,name,status,errors,warnings,translated,import_status,import_errors,import_warnings,imported
0,SJ-1556-1604.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:55:54.481098
1,SJ-1574-1577.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:55:57.758233
2,SJ-1601-1611.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:03.984820
3,SJ-1611-1614.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:07.267389
4,SJ-1615-1620.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:16.951227
5,SJ-1621-1625.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:23.323764
6,SJ-1626-1630.cli,W,0,1,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 14:56:31.833318
7,SJ-1631-1635.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:38.224315
8,SJ-1636-1640.cli,W,0,46,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:46.626443
9,SJ-1641-1645.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:56:54.057129
10,SJ-1646-1649.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:00.852629
11,SJ-1650-1655.cli,W,0,3,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:08.995756
12,SJ-1656-1660.cli,E,1,2,2026-10-12 06:10:00+00:00,N,0,0,NaT
13,SJ-1661-1665.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:14.801733
14,SJ-1666-1670.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:21.367815
15,SJ-1671-1680.cli,E,2,3,2026-10-12 06:10:00+00:00,N,0,0,NaT
16,SJ-1681-1685.cli,W,0,2,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:30.091370
17,SJ-1686-1690.cli,W,0,3,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:42.912856
18,SJ-1691-1697.cli,W,0,8,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:57:56.476017
19,SJ-1698-1700.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:58:03.862778
20,SJ-1701-1702.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:58:16.843605
21,SJ-1703-1704.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:59:13.558129
22,SJ-1705-1706.cli,W,0,1,2026-10-12 06:10:00+00:00,I,0,0,2026-10-12 14:59:21.081209
23,SJ-1707-1708.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:28.306923
24,SJ-1709-1710.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:36.121424
25,SJ-1711-1712.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:41.225458
26,SJ-1713-1714.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:49.138031
27,SJ-1715-1716.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 14:59:57.637989
28,SJ-1717-1718.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:04.736833
29,SJ-1719-1720.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:12.535274
30,SJ-1721-1722.cli,E,1,2,2026-10-12 06:11:00+00:00,N,0,0,NaT
31,SJ-1723-1724.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:20.081107
32,SJ-1725-1727.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:31.124137
33,SJ-1727-1729.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:43.148718
34,SJ-1729-1731.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:50.094365
35,SJ-1732-1733.cli,E,1,1,2026-10-12 06:11:00+00:00,N,0,0,NaT
36,SJ-1734-1735.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:00:56.353300
37,SJ-1736-1737.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:01.733330
38,SJ-1738-1739.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:06.864231
39,SJ-1740-1741.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:14.572256
40,SJ-1742-1743.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:01:23.470793
41,SJ-1744-1745.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:04:46.210006
42,SJ-1745-1746.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:05:46.346975
43,SJ-1747-1748.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:06:30.048051
44,SJ-1749-1750.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:07:13.547600
45,SJ-1751-1752.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:07:48.451266
46,SJ-1753-1754.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:08:23.413842
47,SJ-1755-1756.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:09:22.933552
48,SJ-1757-1758.cli,W,0,1,2026-10-12 06:11:00+00:00,I,0,0,2026-10-12 15:10:05.413562
49,SJ-1759-1760.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:10:28.662415
50,SJ-1761-1762.cli,E,1,2,2026-10-12 06:12:00+00:00,N,0,0,NaT
51,SJ-1763-1764.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:10:47.644973
52,SJ-1765-1766.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:08.476477
53,SJ-1767-1768.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:30.355082
54,SJ-1769-1770.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:11:57.017318
55,SJ-1771-1772.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:12:18.057870
56,SJ-1773-1774.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:12:49.738999
57,SJ-1775-1776.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:13:23.254391
58,SJ-1777-1778.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:13:57.569667
59,SJ-1779-1780.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:14:29.283289
60,SJ-1781-1782.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:16:11.646049
61,SJ-1783-1784.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:19:21.930654
62,SJ-1785-1786.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:21:18.859295
63,SJ-1787-1788.cli,W,0,1,2026-10-12 06:12:00+00:00,I,0,0,2026-10-12 15:22:02.407391
64,SJ-1789-1790.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:22:52.287602
65,SJ-1791-1792.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:23:23.498863
66,SJ-1793-1794.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:24:05.573557
67,SJ-1795-1796.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:24:33.169354
68,SJ-1797-1798.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:25:37.262334
69,SJ-1799-1800.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:21.831890
70,SJ-cas1541-1635.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:29.993169
71,SJ-cas1702-1707.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:26:44.448668
72,SJ-cas1708-1718.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:27:06.700598
73,SJ-cas1719-1726.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:27:46.880646
74,SJ-cas1727-1732.cli,E,7,8,2026-10-12 06:13:00+00:00,N,0,0,NaT
75,SJ-cas1733-1737.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:28:17.782562
76,SJ-cas1738-1739.cli,W,0,1,2026-10-12 06:13:00+00:00,I,0,0,2026-10-12 15:28:27.675109
77,SJ-cas1740-1749.cli,E,10,11,2026-10-12 06:14:00+00:00,N,0,0,NaT
78,SJ-cas1750-1760.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:29:34.809641
79,SJ-cas1761-1770.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:30:37.380827
80,SJ-cas1771-1780.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:31:26.715777
81,SJ-cas1781-1790.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:32:33.585227
82,SJ-cas1791-1800.cli,W,0,1,2026-10-12 06:14:00+00:00,I,0,0,2026-10-12 15:33:33.970349
83,SJ-o1538-1559.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
84,SJ-o1560-1569.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
85,SJ-o1584-1585.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
86,SJ-o1586-1590.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
87,SJ-o1591-1595.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
88,SJ-o1596-1600.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
89,SJ-o1601-1605.cli,W,0,3,2026-10-12 06:15:00+00:00,N,0,0,NaT
90,SJ-o1606-1609.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
91,SJ-o1616-1620.cli,W,0,1,2026-10-12 06:14:00+00:00,N,0,0,NaT
92,SJ-o1621-1625.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
93,SJ-o1622-1623.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
94,SJ-o1626-1630.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
95,SJ-o1631-1635.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
96,SJ-o1636-1640.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
97,SJ-o1641-1645.cli,W,0,2,2026-10-12 06:15:00+00:00,N,0,0,NaT
98,SJ-o1646-1650.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
99,SJ-o1651-1655.cli,W,0,4,2026-10-12 06:15:00+00:00,N,0,0,NaT
100,SJ-o1656-1660.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
101,SJ-o1661-1670.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
102,SJ-o1671-1680.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
103,SJ-o1681-1690.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
104,SJ-o1691-1701.cli,E,11,2,2026-10-12 06:15:00+00:00,N,0,0,NaT
105,SJ-o1702-1710.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
106,SJ-o1711-1720.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
107,SJ-o1721-1725.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
108,SJ-o1726-1730.cli,W,0,1,2026-10-12 06:15:00+00:00,N,0,0,NaT
109,SJ-o1731-1735.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
110,SJ-o1736-1739.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
111,SJ-o1740-1745.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
112,SJ-o1746-1750.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
113,SJ-o1751-1755.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
114,SJ-o1756-1760.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
115,SJ-o1761-1765.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
116,SJ-o1766-1770.cli,W,0,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
117,SJ-o1771-1775.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
118,SJ-o1776-1780.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
119,SJ-o1781-1785.cli,E,11,1,2026-10-12 06:16:00+00:00,N,0,0,NaT
120,SJ-o1786-1790.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
121,SJ-o1791-1793.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
122,SJ-o1794-1795.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
123,SJ-o1796-1800.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
124,ST o1759-1761.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
125,ST o1762-1769.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
126,ST o1770-1774.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
127,ST o1774-1779.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
128,ST o1780-1782.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
129,ST o1783-1786.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
130,ST o1787-1791.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
131,ST o1792-1796.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
132,ST o1797-1800.cli,W,0,1,2026-10-12 06:17:00+00:00,N,0,0,NaT
133,ST obit1751-1755.cli,W,0,1,2026-10-12 06:18:00+00:00,N,0,0,NaT
134,ST obit1756-1758.cli,W,0,1,2026-10-12 06:18:00+00:00,N,0,0,NaT
135,ST-1600-1608.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:34:19.430128
136,ST-1609-1616.cli,E,4,5,2026-10-12 06:18:00+00:00,N,0,0,NaT
137,ST-1616-1624.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:34:56.109711
138,ST-1624-1631.cli,W,0,1,2026-10-12 06:18:00+00:00,I,0,0,2026-10-12 15:35:29.347045
139,ST-1631-1640.cli,E,5,6,2026-10-12 06:18:00+00:00,N,0,0,NaT
140,ST-1640-1643.cli,E,27,28,2026-10-12 06:18:00+00:00,N,0,0,NaT
141,ST-1685-1694.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:10.214362
142,ST-1694-1703.cli,E,35,36,2026-10-12 06:19:00+00:00,N,0,0,NaT
143,ST-1703-1710.cli,E,21,22,2026-10-12 06:19:00+00:00,N,0,0,NaT
144,ST-1710-1716.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:30.399075
145,ST-1716-1719.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:41.545280
146,ST-1719-1722.cli,E,1,2,2026-10-12 06:19:00+00:00,N,0,0,NaT
147,ST-1723-1726.cli,W,0,1,2026-10-12 06:19:00+00:00,I,0,0,2026-10-12 15:36:50.726767
148,ST-1726-1729.cli,E,2,4,2026-10-12 06:20:00+00:00,N,0,0,NaT
149,ST-1730-1733.cli,E,2,3,2026-10-12 06:20:00+00:00,N,0,0,NaT
150,ST-1733-1736.cli,E,2,3,2026-10-12 06:20:00+00:00,N,0,0,NaT
151,ST-1737-1740.cli,E,1,2,2026-10-12 06:20:00+00:00,N,0,0,NaT
152,ST-1740-1743.cli,E,1,2,2026-10-12 06:20:00+00:00,N,0,0,NaT
153,ST-1743-1747.cli,W,0,1,2026-10-12 06:20:00+00:00,I,0,0,2026-10-12 15:37:03.384709
154,ST-1747.cli,W,0,1,2026-10-12 06:20:00+00:00,I,0,0,2026-10-12 15:37:06.912080
155,ST-1764-1766.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:14.265459
156,ST-1767-1769.cli,E,1,4,2026-10-12 06:21:00+00:00,N,0,0,NaT
157,ST-1770-1773.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:21.894859
158,ST-1773-1776.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:29.068873
159,ST-1776-1779.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:37.264681
160,ST-1779-1782.cli,W,0,2,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:37:48.223389
161,ST-1783-1785.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:38:04.882855
162,ST-1785-1788.cli,W,0,1,2026-10-12 06:21:00+00:00,I,0,0,2026-10-12 15:38:18.934370
163,ST-1789-1792.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:38:36.431775
164,ST-1792-1795.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:38:45.507134
165,ST-1796-1800.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:15.229842
166,ST-c1599-1624.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:22.761457
167,ST-c1624-1644.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:40.606841
168,ST-c1695-1705.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:39:58.299862
169,ST-c1706-1721.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:16.012466
170,ST-c1722-1730.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:31.990590
171,ST-c1731-1740.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:40:55.406327
172,ST-c1741-1750.cli,W,0,1,2026-10-12 06:22:00+00:00,I,0,0,2026-10-12 15:41:22.387760
173,ST-c1751-1760.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:41:40.528629
174,ST-c1761-1775.cli,E,1,2,2026-10-12 06:23:00+00:00,N,0,0,NaT
175,ST-c1776-1792.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:41:53.934117
176,ST-c1793-1800.cli,W,0,1,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:03.883282
177,ST-o1599-1626.cli,W,0,1,2026-10-12 06:23:00+00:00,N,0,0,NaT
178,ST-o1626-1631.cli,W,0,1,2026-10-12 06:23:00+00:00,N,0,0,NaT
179,ST-o1632-1643.cli,W,0,9,2026-10-12 06:23:00+00:00,N,0,0,NaT
180,notarial1704.cli,E,1,19,2026-10-12 06:23:00+00:00,N,0,0,NaT
181,notarial1705.cli,E,3,16,2026-10-12 14:55:00+00:00,N,0,0,NaT
182,santamaria-1562-1563.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:06.960262
183,santamaria-1563-1565.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:14.201826
184,santamaria-1566-1570.cli,W,0,2,2026-10-12 06:23:00+00:00,I,0,0,2026-10-12 15:42:36.137971
185,santamaria-1571-1575.cli,E,3,4,2026-10-12 06:23:00+00:00,N,0,0,NaT
186,santamaria-1576-1580.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:42:58.766210
187,santamaria-1581-1584.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:43:10.885025
188,santamaria-1585-1590.cli,E,3,5,2026-10-12 06:24:00+00:00,N,0,0,NaT
189,santamaria-1591-1595.cli,E,3,5,2026-10-12 06:24:00+00:00,N,0,0,NaT
190,santamaria-1596-1599.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:43:22.588234
191,santamaria-1599-1604.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:43:47.082280
192,santamaria-1604-1605.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:43:52.339162
193,santamaria-1606-1610.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:13.597686
194,santamaria-1611-1615.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:28.607120
195,santamaria-1616-1620.cli,W,0,3,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:44:40.733982
196,santamaria-1621-1625.cli,W,0,2,2026-10-12 06:24:00+00:00,I,0,0,2026-10-12 15:44:51.573860
197,santamaria-1625-1629.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:02.060647
198,santamaria-1630-1634.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:14.728713
199,santamaria-1635-1640.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:29.046279
200,santamaria-1641-1645.cli,W,0,2,2026-10-12 14:55:00+00:00,I,0,0,2026-10-12 15:45:42.909895
201,santamaria-1646-1650.cli,E,14,6,2026-10-13 06:19:00+00:00,N,0,0,NaT
202,santamaria-1651-1655.cli,E,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
203,santamaria-1656-1660.cli,E,5,8,2026-10-12 06:24:00+00:00,N,0,0,NaT
204,santamaria-1661-1665.cli,E,3,6,2026-10-12 06:24:00+00:00,N,0,0,NaT
205,santamaria-1666-1670.cli,W,0,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
206,santamaria-1671-1675.cli,W,0,3,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:45:53.172179
207,santamaria-1676-1680.cli,W,0,4,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:04.450913
208,santamaria-1681-1685.cli,W,0,2,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:14.007345
209,santamaria-1686-1690.cli,W,0,3,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:27.718536
210,santamaria-1691-1695.cli,E,10,2,2026-10-13 06:19:00+00:00,N,0,0,NaT
211,santamaria-1696-1700.cli,E,4,7,2026-10-13 06:19:00+00:00,N,0,0,NaT
212,santamaria-1701-1705.cli,W,0,2,2026-10-13 06:19:00+00:00,N,0,0,NaT
213,santamaria-1706-1710.cli,E,2,5,2026-10-12 06:25:00+00:00,N,0,0,NaT
214,santamaria-1711-1715.cli,E,11,6,2026-10-12 06:25:00+00:00,N,0,0,NaT
215,santamaria-1716-1720.cli,E,2,11,2026-10-12 06:25:00+00:00,N,0,0,NaT
216,santamaria-1721-1725.cli,E,1,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
217,santamaria-1726-1730.cli,W,0,2,2026-10-12 06:25:00+00:00,I,0,0,2026-10-12 15:46:43.705050
218,santamaria-1731-1735.cli,E,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
219,santamaria-1736-1740.cli,E,26,21,2026-10-13 06:19:00+00:00,N,0,0,NaT
220,santamaria-1741-1743.cli,E,18,13,2026-10-13 06:19:00+00:00,N,0,0,NaT
221,santamaria-1744-1745.cli,E,2,4,2026-10-13 06:19:00+00:00,N,0,0,NaT
222,santamaria-1746-1750.cli,E,1,3,2026-10-12 06:26:00+00:00,N,0,0,NaT
223,santamaria-1751-1753.cli,W,0,5,2026-10-13 06:19:00+00:00,N,0,0,NaT
224,santamaria-1754-1755.cli,W,0,3,2026-10-13 06:19:00+00:00,N,0,0,NaT
225,santamaria-1756-1758.cli,E,10,4,2026-10-12 06:26:00+00:00,N,0,0,NaT
226,santamaria-1759-1760.cli,W,0,2,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:46:55.385632
227,santamaria-1761-1765.cli,E,1,4,2026-10-12 06:26:00+00:00,N,0,0,NaT
228,santamaria-1766-1770.cli,E,10,6,2026-10-13 06:19:00+00:00,N,0,0,NaT
229,santamaria-1771-1774.cli,W,0,7,2026-10-13 06:19:00+00:00,N,0,0,NaT
230,santamaria-1775.cli,E,1,2,2026-10-12 06:26:00+00:00,N,0,0,NaT
231,santamaria-1776-1781.cli,E,12,2,2026-10-12 06:26:00+00:00,N,0,0,NaT
232,santamaria-1782.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:01.004696
233,santamaria-1783.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:05.034417
234,santamaria-1784.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:08.090386
235,santamaria-1785.cli,E,1,2,2026-10-12 06:26:00+00:00,N,0,0,NaT
236,santamaria-1786.cli,E,3,1,2026-10-12 06:26:00+00:00,N,0,0,NaT
237,santamaria-1787-1788.cli,E,1,1,2026-10-12 06:26:00+00:00,N,0,0,NaT
238,santamaria-1789-1791.cli,E,2,3,2026-10-12 06:27:00+00:00,N,0,0,NaT
239,santamaria-1792-1794.cli,E,10,2,2026-10-12 06:27:00+00:00,N,0,0,NaT
240,santamaria-1795.cli,W,0,1,2026-10-12 06:26:00+00:00,I,0,0,2026-10-12 15:47:13.919623
241,santamaria-1796.cli,E,3,2,2026-10-12 06:27:00+00:00,N,0,0,NaT
242,santamaria-1797.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:20.883700
243,santamaria-1798-1800.cli,E,2,3,2026-10-12 06:27:00+00:00,N,0,0,NaT
244,santamaria-c1566-1570.cli,E,12,3,2026-10-13 06:19:00+00:00,N,0,0,NaT
245,santamaria-c1571-1575.cli,W,0,2,2026-10-13 06:19:00+00:00,N,0,0,NaT
246,santamaria-c1576-1580.cli,W,0,2,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:24.369460
247,santamaria-c1581-1585.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:28.073768
248,santamaria-c1586-1590.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:31.076166
249,santamaria-c1591-1595.cli,E,10,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
250,santamaria-c1596-1600.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:33.631759
251,santamaria-c1601-1605.cli,E,11,1,2026-10-12 06:27:00+00:00,N,0,0,NaT
252,santamaria-c1606-1610.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
253,santamaria-c1611-1615.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
254,santamaria-c1616-1620.cli,W,0,1,2026-10-13 06:19:00+00:00,N,0,0,NaT
255,santamaria-c1621-1625.cli,W,0,1,2026-10-12 06:27:00+00:00,I,0,0,2026-10-12 15:47:36.131761

### Check a translation report

If needed to check for errors.

In [23]:

# get the translation status
imported_files_df = tlnb.get_import_status(match_path=True)
errors = imported_files_df[imported_files_df["errors"] > 0 ]
errors[["name", "errors", "warnings", "import_status", "import_errors", "import_warnings", "path"]].sort_values("name")

,name,errors,warnings,import_status,import_errors,import_warnings,path
12,SJ-1656-1660.cli,1,2,N,0,0,sources/paroquiais/sjoao/Baptismos/SJ-1656-166...
15,SJ-1671-1680.cli,2,3,N,0,0,sources/paroquiais/sjoao/Baptismos/SJ-1671-168...
30,SJ-1721-1722.cli,1,2,N,0,0,sources/paroquiais/sjoao/Baptismos/SJ-1721-172...
35,SJ-1732-1733.cli,1,1,N,0,0,sources/paroquiais/sjoao/Baptismos/SJ-1732-173...
50,SJ-1761-1762.cli,1,2,N,0,0,sources/paroquiais/sjoao/Baptismos/SJ-1761-176...
74,SJ-cas1727-1732.cli,7,8,N,0,0,sources/paroquiais/sjoao/Casamentos/SJ-cas1727...
77,SJ-cas1740-1749.cli,10,11,N,0,0,sources/paroquiais/sjoao/Casamentos/SJ-cas1740...
104,SJ-o1691-1701.cli,11,2,N,0,0,sources/paroquiais/sjoao/Óbitos/SJ-o1691-1701...
119,SJ-o1781-1785.cli,11,1,N,0,0,sources/paroquiais/sjoao/Óbitos/SJ-o1781-1785...
136,ST-1609-1616.cli,4,5,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1609-16...
139,ST-1631-1640.cli,5,6,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1631-16...
140,ST-1640-1643.cli,27,28,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1640-16...
142,ST-1694-1703.cli,35,36,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1694-17...
143,ST-1703-1710.cli,21,22,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1703-17...
146,ST-1719-1722.cli,1,2,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1719-17...
148,ST-1726-1729.cli,2,4,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1726-17...
149,ST-1730-1733.cli,2,3,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1730-17...
150,ST-1733-1736.cli,2,3,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1733-17...
151,ST-1737-1740.cli,1,2,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1737-17...
152,ST-1740-1743.cli,1,2,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1740-17...
156,ST-1767-1769.cli,1,4,N,0,0,sources/paroquiais/stiago/Baptismos/ST-1767-17...
174,ST-c1761-1775.cli,1,2,N,0,0,sources/paroquiais/stiago/Casamentos/ST-c1761-...
180,notarial1704.cli,1,19,N,0,0,sources/notariais/joao ferreira serra/notarial...
181,notarial1705.cli,3,16,N,0,0,sources/notariais/joao ferreira serra/notarial...
185,santamaria-1571-1575.cli,3,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
188,santamaria-1585-1590.cli,3,5,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
189,santamaria-1591-1595.cli,3,5,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
201,santamaria-1646-1650.cli,14,6,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
202,santamaria-1651-1655.cli,2,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
203,santamaria-1656-1660.cli,5,8,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
204,santamaria-1661-1665.cli,3,6,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
210,santamaria-1691-1695.cli,10,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
211,santamaria-1696-1700.cli,4,7,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
213,santamaria-1706-1710.cli,2,5,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
214,santamaria-1711-1715.cli,11,6,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
215,santamaria-1716-1720.cli,2,11,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
216,santamaria-1721-1725.cli,1,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
218,santamaria-1731-1735.cli,2,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
219,santamaria-1736-1740.cli,26,21,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
220,santamaria-1741-1743.cli,18,13,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
221,santamaria-1744-1745.cli,2,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
222,santamaria-1746-1750.cli,1,3,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
225,santamaria-1756-1758.cli,10,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
227,santamaria-1761-1765.cli,1,4,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
228,santamaria-1766-1770.cli,10,6,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
230,santamaria-1775.cli,1,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
231,santamaria-1776-1781.cli,12,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
235,santamaria-1785.cli,1,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
236,santamaria-1786.cli,3,1,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
237,santamaria-1787-1788.cli,1,1,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
238,santamaria-1789-1791.cli,2,3,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
239,santamaria-1792-1794.cli,10,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
241,santamaria-1796.cli,3,2,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
243,santamaria-1798-1800.cli,2,3,N,0,0,sources/paroquiais/santamaria/Baptismos/santam...
244,santamaria-c1566-1570.cli,12,3,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
249,santamaria-c1591-1595.cli,10,1,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
251,santamaria-c1601-1605.cli,11,1,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
262,santamaria-c1656-1661.cli,11,2,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
267,santamaria-c1681-1685.cli,11,1,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
277,santamaria-c1731-1733.cli,1,2,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
288,santamaria-c1776-1778.cli,1,1,N,0,0,sources/paroquiais/santamaria/Casamentos/santa...
298,santamaria-o1573-1575.cli,10,2,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
305,santamaria-o1611-1615.cli,10,2,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
310,santamaria-o1626-1630.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
311,santamaria-o1631-1635.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
312,santamaria-o1636-1640.cli,11,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
317,santamaria-o1655-1660.cli,7,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
319,santamaria-o1666-1670.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
321,santamaria-o1676-1680.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
332,santamaria-o1726-1730.cli,10,2,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
335,santamaria-o1756-1758.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
339,santamaria-o1770-1773.cli,10,4,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
350,santamaria-o1794-1796.cli,10,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
352,santamaria-o1798-1799.cli,11,1,N,0,0,sources/paroquiais/santamaria/Óbitos/santamar...
374,saopedro-b1711-1712.cli,11,2,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
378,saopedro-b1720-1721.cli,1,2,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
382,saopedro-b1728-1729.cli,1,1,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
385,saopedro-b1734-1735.cli,10,3,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
391,saopedro-b1746-1747.cli,10,4,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
394,saopedro-b1752-1753.cli,1,2,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
395,saopedro-b1753-1755.cli,1,2,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
396,saopedro-b1756-1757.cli,11,4,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
397,saopedro-b1758-1759.cli,1,2,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
402,saopedro-b1768-1769.cli,1,1,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
415,saopedro-b1793.cli,11,4,N,0,0,sources/paroquiais/spedro/Baptismos/saopedro-b...
435,saopedro-o1775-1776.cli,10,3,N,0,0,sources/paroquiais/spedro/Óbitos/saopedro-o17...
441,saopedro-o1794-1795.cli,10,3,N,0,0,sources/paroquiais/spedro/Óbitos/saopedro-o17...
445,vau-c1761-1765.cli,11,3,N,0,0,sources/paroquiais/vau/Casamentos/vau-c1761-17...
454,vau-o1761-1765.cli,10,2,N,0,0,sources/paroquiais/vau/Óbitos/vau-o1761-1765.cli

### Get the import report for a file

In case there are errors in the import phase check the import report.

In [24]:
ierrors = imported_files_df[imported_files_df.import_errors>0][["import_status", "import_errors","import_warnings","name","imported","errors","warnings","path"]].sort_values("name")
ierrors

Empty DataFrame
Columns: [import_status, import_errors, import_warnings, name, imported, errors, warnings, path]
Index: []

In [25]:
for ierror in ierrors.index:
    print(f"File: {ierrors.loc[ierror,'name']} - {ierrors.loc[ierror,'path']}")
    rpt = tlnb.get_import_rpt(imported_files_df, rows=ierror, match_path=True)
    print(rpt)

### Get a specific import report

In [26]:
rpt = tlnb.get_import_rpt(imported_files_df, rows=[0])
print(rpt)

SJ-1556-1604.cli
No errors
No warnings